Weights:
  VGGT: './weights/model.pt'
  DBoW: './weights/ORBvoc.txt'
  SALAD: './weights/dino_salad.ckpt'
  DNIO: './weights/dinov2_vitb14_pretrain.pth'

Model:
  chunk_size: 60
  overlap: 30
  loop_chunk_size: 20 # imgs of loop chunk = 2 * loop_chunk_size
  loop_enable: False
  useDBoW: False
  delete_temp_files: True
  temp_files_location: 'disk' # choose between 'disk' or 'cpu_memory'
  # [!!Attention!!] Please ensure sufficient CPU memory if you choose 'cpu_memory' for temp_files_location!
  align_lib: 'triton' # choose among 'triton' (GPU), 'torch' (GPU), 'numba' (CPU) or 'numpy' (CPU)
  align_method: 'sim3' # choose among 'sim3', 'se3' or 'scale+se3'
  scale_compute_method: 'auto' # choose among 'auto', 'ransac' or 'weighted'. It is used when align_method == 'scale+se3'
  align_type: 'dense' # choose between 'dense' or 'sparse'. Sparse align is constructing, not avaible for now
  
  reference_frame_mid: False 
  # If reference_frame_mid == True, use the middle frame within the chunk as the 
  # reference frame to alleviate the scale drift when loop closure is not available.
  # Disable it for now cuz i found some bugs related to this feature [by deng on 09 Oct].
  # 如果 reference_frame_mid 为 True，则使用块内的中间帧作为 
  # 当回环闭合不可用时，用于缓解尺度漂移的参考帧。
  # 目前先禁用它，因为我发现了一些与此功能相关的错误 [邓于10月9日发现]。
  
  Sparse_Align:
    keypoint_select: 'orb' # choose among 'orb', 'fast' or 'disk'
    keypoint_num: 5000

  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

  Pointcloud_Save:
    sample_ratio: 0.015
    conf_threshold_coef: 0.75 # conf_threshold = np.mean(confs) * conf_threshold_coef

Loop:
  DBoW:
    thresh: 0.034
    num_repeat: 3
    NMS: 25

  SALAD:
    image_size: [336, 336]
    batch_size: 32
    similarity_threshold: 0.7
    top_k: 5
    use_nms: True
    nms_threshold: 25

  SIM3_Optimizer:
    lang_version: 'cpp' 
    # choose between 'cpp' or 'python'. will auto set 'python' if c++ version has not installed
    max_iterations: 30
    lambda_init: 1e-6
